### ISSUE TITLE
Error in e329a2f79be94ce289a8002f1f174340.glb (Objaverse dataset)

### ISSUE THREAD

**Issue by Fangkang515** [Pointcept/SAMPart3D#18]
Thanks for your work. 

I found that this code will go wrong in some scenarios, such as e329a2f79be94ce289a8002f1f174340.glb in Objaverse dataset.

```
ValueError: Trainer: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by QuantileTransformer.
```

Could you please test it out? I am still unable to precisely locate where the problem lies.

Thank you so much~

**Comment by eiiijiiiy** [comment]
In my case, this is due to the out of memory issue of GPU, making SAM producing no masks. This leads to an empty `scales` array for `quantile_transformer.fit(scales.reshape(-1, 1))`.

**Comment by JarneVdH** [comment]
I had the same issue as OP and this was caused by a compatibility issue between torch and torchvision. This caused the SAM call to fail, where the error was invisible at first because of the general try-except block here: https://github.com/Pointcept/SAMPart3D/blob/6a508d145be5cecd7e80bce6e4248ea7abbd71b7/pointcept/datasets/dataset_render_16views.py#L173-L178

Upon inspecting the error I saw the following:

```
Error processing frame_0: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```

After re-installing the environment with special care for some packages, it worked.

**Comment by Tommy881003** [comment]
Hi, sorry for jumping in — I’m trying to get the project running on my device, but I’ve been running into a lot of dependency conflicts and missing models. Would you be willing to share either:
- the output of your pip list (or conda list), so I can match the package versions, or
- even better, if you happen to have a working environment.yml or Dockerfile, that would be a lifesaver.

I’ve already tried setting up with:
- Python 3.10 / PyTorch 2.1.0 (CUDA 12.1)
- Installing flash-attention and other requirements

…but I still keep hitting errors like missing libcublas.so.11 or undefined symbol.
Totally understand if you don’t have time, but even a rough list of the versions you used would help a lot. Thanks!

**Comment by Leader-sheng** [comment]
good job [JarneVdH]!!!
